server:
  port: 9002

spring:
  application:
    name: zipkin-producer
  sleuth:
    sampler:
      probability: 1 # 采集率，测试时用1， 上生产并发高的时候用0.01或者更低
    feign:
      enabled: true
  zipkin:
    base-url: http://centos7:9411
    sender:
      type: rabbit
  rabbitmq:
    addresses: centos7:5672
    username: admin
    password: admin